# Deploy OpenShift Container Platform
# Uses Fork of https://github.com/microsoft/openshift-container-platform
# https://github.com/ATALLC/openshift-container-platform

trigger:
- none

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: 'smartFMAgentPool'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              sed -i.bak 's|OSADMINUSERNAME|$(OS_ADMIN_USER_NAME)|g' azuredeploy.parameters.json
              sed -i.bak 's|IMGPUBLISHER|$(IMG_PUBLISHER)|g' azuredeploy.parameters.json
              sed -i.bak 's|IMGOFFER|$(IMG_OFFER)|g' azuredeploy.parameters.json
              sed -i.bak 's|IMGSKU|$(IMG_SKU)|g' azuredeploy.parameters.json
              sed -i.bak 's|IMGVERSION|$(IMG_VERSION)|g' azuredeploy.parameters.json
              sed -i.bak 's|MASTERCOUNT|$(MASTER_COUNT)|g' azuredeploy.parameters.json
              sed -i.bak 's|INFRCOUNT|$(INFR_COUNT)|g' azuredeploy.parameters.json
              sed -i.bak 's|NODECOUNT|$(NODE_COUNT)|g' azuredeploy.parameters.json
              sed -i.bak 's|RHSMORGID|$(RHSM_ORG_ID)|g' azuredeploy.parameters.json
              sed -i.bak 's|RHSMPOOLID|$(RHSM_POOL_ID)|g' azuredeploy.parameters.json
              sed -i.bak 's|SSHPUBLICKEY|$(SSH_PUBLIC_KEY)|g' azuredeploy.parameters.json
              sed -i.bak 's|KEYVAULTSUBSCRIPTIONID|$(KEYVAULT_SUBSCRIPTION_ID)|g' azuredeploy.parameters.json
              sed -i.bak 's|KEYVAULTRESOURCEGROUP|$(KEYVAULT_RESOURCE_GROUP)|g' azuredeploy.parameters.json
              sed -i.bak 's|KEYVAULTNAME|$(KEY_VAULT_NAME)|g' azuredeploy.parameters.json
              sed -i.bak 's|AADCLIENTID|$(AAD_CLIENT_ID)|g' azuredeploy.parameters.json
            displayName: 'Update variables in parameter file from pipeline variables'
          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create Or Update Resource Group action on ADO Agent'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              resourceGroupName: $(RESOURCE_GROUP)
              location: 'East US'
              csmFile: 'azuredeploy.json'
              csmParametersFile: 'azuredeploy.parameters.json'