# Deploy OpenShift Container Platform Utilizing ENV_PARAMETERS_FILE variable to specify the file in the envs folder. 
# Uses Fork of https://github.com/microsoft/openshift-container-platform
# https://github.com/ATALLC/openshift-container-platform

trigger:
- none

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: 'smartFMAgentPool'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create Or Update Resource Group action on ADO Agent'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              resourceGroupName: $(RESOURCE_GROUP)
              location: 'East US'
              csmFile: 'azuredeploy.json'
              csmParametersFile: 'envs/$(ENV_PARAMETERS_FILE)'